CRITICAL - 2022-12-19 08:43:09 --> Expired token
#0 C:\symfony-docker\php-project\app\Filters\AuthFilter.php(67): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', Object(Firebase\JWT\Key))
#1 C:\symfony-docker\php-project\system\Filters\Filters.php(196): App\Filters\AuthFilter->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), NULL)
#2 C:\symfony-docker\php-project\system\CodeIgniter.php(436): CodeIgniter\Filters\Filters->run('crop', 'after')
#3 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#5 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#6 {main}
CRITICAL - 2022-12-19 13:48:02 --> Expired token
#0 C:\symfony-docker\php-project\app\Filters\AuthFilter.php(67): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', Object(Firebase\JWT\Key))
#1 C:\symfony-docker\php-project\system\Filters\Filters.php(196): App\Filters\AuthFilter->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), NULL)
#2 C:\symfony-docker\php-project\system\CodeIgniter.php(436): CodeIgniter\Filters\Filters->run('measurement', 'after')
#3 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#5 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#6 {main}
CRITICAL - 2022-12-19 13:49:22 --> Undefined offset: 1
#0 C:\symfony-docker\php-project\app\Controllers\Measurement.php(58): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\\symfony-dock...', 58, Array)
#1 C:\symfony-docker\php-project\system\CodeIgniter.php(832): App\Controllers\Measurement->create2()
#2 C:\symfony-docker\php-project\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Measurement))
#3 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#5 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#6 {main}
CRITICAL - 2022-12-19 13:51:35 --> Undefined index: data
#0 C:\symfony-docker\php-project\app\Controllers\Measurement.php(54): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\symfony-dock...', 54, Array)
#1 C:\symfony-docker\php-project\system\CodeIgniter.php(832): App\Controllers\Measurement->create2()
#2 C:\symfony-docker\php-project\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Measurement))
#3 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#5 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#6 {main}
CRITICAL - 2022-12-19 13:51:39 --> Undefined index: data
#0 C:\symfony-docker\php-project\app\Controllers\Measurement.php(54): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\symfony-dock...', 54, Array)
#1 C:\symfony-docker\php-project\system\CodeIgniter.php(832): App\Controllers\Measurement->create2()
#2 C:\symfony-docker\php-project\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Measurement))
#3 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#5 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#6 {main}
CRITICAL - 2022-12-19 13:52:06 --> explode() expects parameter 2 to be string, array given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'explode() expec...', 'C:\\symfony-dock...', 54, Array)
#1 C:\symfony-docker\php-project\app\Controllers\Measurement.php(54): explode(',', Array)
#2 C:\symfony-docker\php-project\system\CodeIgniter.php(832): App\Controllers\Measurement->create2()
#3 C:\symfony-docker\php-project\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Measurement))
#4 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#6 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#7 {main}
ERROR - 2022-12-19 13:52:43 --> Cannot add or update a child row: a foreign key constraint fails (`sai_ecaa`.`t_mediciones`, CONSTRAINT `FK_CICLO` FOREIGN KEY (`CIC_CODIGO`) REFERENCES `t_ciclo_cultivo` (`CIC_CODIGO`))
CRITICAL - 2022-12-19 13:52:43 --> Cannot add or update a child row: a foreign key constraint fails (`sai_ecaa`.`t_mediciones`, CONSTRAINT `FK_CICLO` FOREIGN KEY (`CIC_CODIGO`) REFERENCES `t_ciclo_cultivo` (`CIC_CODIGO`))
#0 C:\symfony-docker\php-project\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `t_...', 0)
#1 C:\symfony-docker\php-project\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `t_...')
#2 C:\symfony-docker\php-project\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `t_...')
#3 C:\symfony-docker\php-project\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `t_...', Array, false)
#4 C:\symfony-docker\php-project\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\symfony-docker\php-project\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\symfony-docker\php-project\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\symfony-docker\php-project\system\BaseModel.php(658): CodeIgniter\Model->insert(Object(App\Entities\Measurement), false)
#8 C:\symfony-docker\php-project\app\Controllers\Measurement.php(62): CodeIgniter\BaseModel->save(Object(App\Entities\Measurement))
#9 C:\symfony-docker\php-project\system\CodeIgniter.php(832): App\Controllers\Measurement->create2()
#10 C:\symfony-docker\php-project\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Measurement))
#11 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#13 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#14 {main}
ERROR - 2022-12-19 13:53:06 --> Cannot add or update a child row: a foreign key constraint fails (`sai_ecaa`.`t_mediciones`, CONSTRAINT `FK_CICLO` FOREIGN KEY (`CIC_CODIGO`) REFERENCES `t_ciclo_cultivo` (`CIC_CODIGO`))
CRITICAL - 2022-12-19 13:53:06 --> Cannot add or update a child row: a foreign key constraint fails (`sai_ecaa`.`t_mediciones`, CONSTRAINT `FK_CICLO` FOREIGN KEY (`CIC_CODIGO`) REFERENCES `t_ciclo_cultivo` (`CIC_CODIGO`))
#0 C:\symfony-docker\php-project\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `t_...', 0)
#1 C:\symfony-docker\php-project\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `t_...')
#2 C:\symfony-docker\php-project\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `t_...')
#3 C:\symfony-docker\php-project\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `t_...', Array, false)
#4 C:\symfony-docker\php-project\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\symfony-docker\php-project\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\symfony-docker\php-project\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\symfony-docker\php-project\system\BaseModel.php(658): CodeIgniter\Model->insert(Object(App\Entities\Measurement), false)
#8 C:\symfony-docker\php-project\app\Controllers\Measurement.php(62): CodeIgniter\BaseModel->save(Object(App\Entities\Measurement))
#9 C:\symfony-docker\php-project\system\CodeIgniter.php(832): App\Controllers\Measurement->create2()
#10 C:\symfony-docker\php-project\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Measurement))
#11 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#13 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#14 {main}
ERROR - 2022-12-19 13:53:21 --> Cannot add or update a child row: a foreign key constraint fails (`sai_ecaa`.`t_mediciones`, CONSTRAINT `FK_CICLO` FOREIGN KEY (`CIC_CODIGO`) REFERENCES `t_ciclo_cultivo` (`CIC_CODIGO`))
CRITICAL - 2022-12-19 13:53:21 --> Cannot add or update a child row: a foreign key constraint fails (`sai_ecaa`.`t_mediciones`, CONSTRAINT `FK_CICLO` FOREIGN KEY (`CIC_CODIGO`) REFERENCES `t_ciclo_cultivo` (`CIC_CODIGO`))
#0 C:\symfony-docker\php-project\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `t_...', 0)
#1 C:\symfony-docker\php-project\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `t_...')
#2 C:\symfony-docker\php-project\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `t_...')
#3 C:\symfony-docker\php-project\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `t_...', Array, false)
#4 C:\symfony-docker\php-project\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\symfony-docker\php-project\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\symfony-docker\php-project\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\symfony-docker\php-project\system\BaseModel.php(658): CodeIgniter\Model->insert(Object(App\Entities\Measurement), false)
#8 C:\symfony-docker\php-project\app\Controllers\Measurement.php(62): CodeIgniter\BaseModel->save(Object(App\Entities\Measurement))
#9 C:\symfony-docker\php-project\system\CodeIgniter.php(832): App\Controllers\Measurement->create2()
#10 C:\symfony-docker\php-project\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Measurement))
#11 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#13 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#14 {main}
ERROR - 2022-12-19 13:55:35 --> Cannot add or update a child row: a foreign key constraint fails (`sai_ecaa`.`t_mediciones`, CONSTRAINT `FK_CICLO` FOREIGN KEY (`CIC_CODIGO`) REFERENCES `t_ciclo_cultivo` (`CIC_CODIGO`))
CRITICAL - 2022-12-19 13:55:35 --> Cannot add or update a child row: a foreign key constraint fails (`sai_ecaa`.`t_mediciones`, CONSTRAINT `FK_CICLO` FOREIGN KEY (`CIC_CODIGO`) REFERENCES `t_ciclo_cultivo` (`CIC_CODIGO`))
#0 C:\symfony-docker\php-project\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `t_...', 0)
#1 C:\symfony-docker\php-project\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `t_...')
#2 C:\symfony-docker\php-project\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `t_...')
#3 C:\symfony-docker\php-project\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `t_...', Array, false)
#4 C:\symfony-docker\php-project\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\symfony-docker\php-project\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\symfony-docker\php-project\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\symfony-docker\php-project\system\BaseModel.php(658): CodeIgniter\Model->insert(Object(App\Entities\Measurement), false)
#8 C:\symfony-docker\php-project\app\Controllers\Measurement.php(62): CodeIgniter\BaseModel->save(Object(App\Entities\Measurement))
#9 C:\symfony-docker\php-project\system\CodeIgniter.php(832): App\Controllers\Measurement->create2()
#10 C:\symfony-docker\php-project\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Measurement))
#11 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#13 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#14 {main}
CRITICAL - 2022-12-19 13:56:55 --> Expired token
#0 C:\symfony-docker\php-project\app\Filters\AuthFilter.php(67): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', Object(Firebase\JWT\Key))
#1 C:\symfony-docker\php-project\system\Filters\Filters.php(196): App\Filters\AuthFilter->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), NULL)
#2 C:\symfony-docker\php-project\system\CodeIgniter.php(436): CodeIgniter\Filters\Filters->run('cropCycle', 'after')
#3 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#5 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#6 {main}
CRITICAL - 2022-12-19 13:57:50 --> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://oauth2.googleapis.com/token
#0 C:\symfony-docker\php-project\vendor\kreait\firebase-php\src\Firebase\Exception\DatabaseApiExceptionConverter.php(34): Kreait\Firebase\Exception\DatabaseApiExceptionConverter->convertGuzzleRequestException(Object(GuzzleHttp\Exception\RequestException))
#1 C:\symfony-docker\php-project\vendor\kreait\firebase-php\src\Firebase\Database\ApiClient.php(194): Kreait\Firebase\Exception\DatabaseApiExceptionConverter->convertException(Object(GuzzleHttp\Exception\RequestException))
#2 C:\symfony-docker\php-project\vendor\kreait\firebase-php\src\Firebase\Database\ApiClient.php(86): Kreait\Firebase\Database\ApiClient->requestApi('PUT', Object(GuzzleHttp\Psr7\Uri), Array)
#3 C:\symfony-docker\php-project\vendor\kreait\firebase-php\src\Firebase\Database\Reference.php(293): Kreait\Firebase\Database\ApiClient->set(Object(GuzzleHttp\Psr7\Uri), Array)
#4 C:\symfony-docker\php-project\app\Helpers\firebase_helper.php(8): Kreait\Firebase\Database\Reference->set(Array)
#5 C:\symfony-docker\php-project\app\Controllers\Measurement.php(74): setData('', Array)
#6 C:\symfony-docker\php-project\system\CodeIgniter.php(832): App\Controllers\Measurement->create2()
#7 C:\symfony-docker\php-project\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Measurement))
#8 C:\symfony-docker\php-project\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\symfony-docker\php-project\public\index.php(39): CodeIgniter\CodeIgniter->run()
#10 C:\symfony-docker\php-project\system\Commands\Server\rewrite.php(43): require_once('C:\\symfony-dock...')
#11 {main}
